### ISSUE TITLE
The "Site search" functionality doesn't work

### ISSUE THREAD

**Issue by AJK-dev** [protwis/protwis#173]
The **Site search from PDB complex** option hasn't been working for a long time (at least for 2 years).

There are multiple issues that caused this:
- the interaction types have been redefined - now mixing old and new
- the amino acid groups have been redefined - now mixing old and new
- the template system doesn't have variables with the definition of the old groups
- the wrong residue numbers are assigned to the interacting residues (see issue #174) 
- extra: the snakeplot and boxplot options are called when using this function, should be prevented

**Comment by esguerra** [comment]
Ooops!
Guess it's better to wait until it gets deployed.

**Comment by AJK-dev** [comment]
Jeps ;-) By referencing the issue in the PR/commits with the right tag it will automatically close once it's deploying/merged into master.
