### ISSUE TITLE
Interaction page is broken for a few structures

### ISSUE THREAD

**Issue by AJK-dev** [protwis/protwis#228]
For a few structures the interaction page returns an error instead of being correctly rendered.

Possibly, this issue is due to an interacting residue with a generic number for the structure, but not the wildtype sequence.
Output from BLC:
├─BROKEN─ https://gpcrdb.org/interaction/6RZ9 (HTTP_500)
├─BROKEN─ https://gpcrdb.org/interaction/6RZ7 (HTTP_500)
├─BROKEN─ https://gpcrdb.org/interaction/6RZ8 (HTTP_500)
├─BROKEN─ https://gpcrdb.org/interaction/6WI9 (HTTP_500)
├─BROKEN─ https://gpcrdb.org/interaction/6WZG (HTTP_500)

**Comment by esguerra** [comment]
Also, why are all structures displayed twice in ngl? Is it supposed to be a stereo image? If so, using an orthoscopic projection to turn off the perspective display would be needed.

**Comment by AJK-dev** [comment]
> Also, why are all structures displayed twice in ngl? Is it supposed to be a stereo image? If so, using an orthoscopic projection to turn off the perspective display would be needed.

@esguerra Could you provide an example? I've never seen this behavior.

**Comment by esguerra** [comment]
<img width="1237" alt="Screen Shot 2020-10-26 at 10 59 16" src="https://user-images.githubusercontent.com/107724/97158990-7b7a6580-177a-11eb-9d14-733b3de0eb54.png">

For example. Every structure I've tried comes out "in pairs"

**Comment by AJK-dev** [comment]
Ah thanks for the example, in these cases it's because of there are two (or sometimes more) chains in the unit cell.
The NGL viewer shows the full PDB, not only the preferred chain. I'll make a feature and combine it with another "nice to have" for the NGL viewer.
