### ISSUE TITLE
Error when downloading PDB structures 

### ISSUE THREAD

**Issue by cbouy** [protwis/protwis#280]
Hi,

I'm receiving an error when I try to download PDB structures from the Receptors>Structures page.
Here's how to reproduce the error:

* Go to Receptors > Structures 
* Click on "Download PDBs"
* Click on "Prepare structures"
* Click on Download > Full proteins

URL: `https://gpcrdb.org/structure/pdb_download/full`
```
Server error
There was an error handling your request. Either the url you entered is incorrect or it was something on our end.

If you believe this is an error on our end, please do not hesitate to contact us on info@gpcrdb.org.

Do you have a Github account? In that case you can directly report your issue on our GitHub issues page.
```
It does the same error with "advanced segment selection" (after selecting the TMs for example) instead of "full proteins"

It would be great if this could be fixed, especially for the advanced segment selection!

Thanks,
Cédric

**Comment by esguerra** [comment]
> Hi,
> 
> I'm receiving an error when I try to download PDB structures from the Receptors>Structures page.
> Here's how to reproduce the error:
> 
>     * Go to Receptors > Structures
> 
>     * Click on "Download PDBs"
> 
>     * Click on "Prepare structures"
> 
>     * Click on Download > Full proteins
> 
> 
> URL: `https://gpcrdb.org/structure/pdb_download/full`
> 
> ```
> Server error
> There was an error handling your request. Either the url you entered is incorrect or it was something on our end.
> 
> If you believe this is an error on our end, please do not hesitate to contact us on info@gpcrdb.org.
> 
> Do you have a Github account? In that case you can directly report your issue on our GitHub issues page.
> ```
> 
> It does the same error with "advanced segment selection" (after selecting the TMs for example) instead of "full proteins"
> 
> It would be great if this could be fixed, especially for the advanced segment selection!
> 
> Thanks,
> Cédric

Hi Cedric,
How many structures did you select? or which structure did you select?
Maybe a naive comment, but try ticking on different sets of selection boxes in the first column of the table?
I have just tested your workflow and it works well for me, thus far.

**Comment by cbouy** [comment]
Oh nevermind I actually forgot to select the structures in the first place... 😅
Thanks for the quick response though

**Comment by cbouy** [comment]
Re-opening this as it works when selecting 1 or 2 structures but not 10 or more!
I can understand if there's a limit to the number of structures one can download, but not being able to fetch 10 structures seems a bit off.

**Comment by AJK-dev** [comment]
Thanks for the feedback Cédric.

Just a quick update: we have tweaked the server configuration so now you can download up to 50 structures at the same time without an issue (please verify if this also works for you). In the meantime, we are working on an update that will allow to download up to a 100 structures in one go and also provide you with some feedback if you did not select any structures or go beyond a 100 structures. 

@pszgaspar will link and close this issue when this implementation is finished and online.

**Comment by cbouy** [comment]
@AJK-dev thanks for the update, I can confirm that it works with 43 structures on my end (I didn't try more).

> we are working on an update that will allow to download up to a 100 structures in one go and also provide you with some feedback if you did not select any structures or go beyond a 100 structures.

That would be great, thank you!
