### ISSUE TITLE
Advanced segment selection when downloading structures

### ISSUE THREAD

**Issue by cbouy** [protwis/protwis#283]
Hi, I think I discovered 2 related issues:

**Issue A:**
When downloading the structure of the dopamine D2 receptor (PDB: 7DFP) from the Receptors > Structures page, after selecting the TMs (1 to 7) with the "Advanced segment selection" I noticed that the resulting PDB file just contains some parts of the TMs and not all of the residues that belong to the TMs as one would expect:
![2021-01-19-134043_524x658_scrot](https://user-images.githubusercontent.com/27850535/105035884-fdb5b580-5a5b-11eb-8c7f-c353e27d306b.png)
When downloading the full protein, all of the TM residues are there so it's not a structure cleaning problem.

**Issue B:**
Another more concerning problem is that when I select multiple structures and go through the same TM segment selection, only one of the resulting PDB files seem to contain all of the TM residues, the other files contain a mix of TMs and loops. In my case I selected 7DFP, 6LPK, 7BR3 and 6WGT (in this order) and only 6WGT contains exclusively the TMs. The other files contain  loops and fragments of helices.
Note that 6WGT is both the last entry I selected in the structure table, and the first one in filename alphabetical order ("5ht2a_human_6WGT").

PS: the two PDB files corresponding to 7DFP are different in issue A and B

**Comment by pszgaspar** [comment]
Hi Cédric,
Thanks for the bug report. When looking into the pdb structure download issue I also ran into this. It seems there are multiple simultaneous issues going on here, one being incorrect generic number assignment (Issue A) so only a portion of residues get selected and the second being that when selecting multiple structures, the residue selection is not updated between structures so the same residue numbers are fetched for every structure. I will make a fix for this later and close this thread when it's online.
