### ISSUE TITLE
Alignment column sorting and consensus rendering

### ISSUE THREAD

**Issue by AlexanderHauser** [protwis/protwis#39]
with the consensus, there seems to be an offset, due to the gaps in 6x29 in many proteins (see img below)

and with the column names, they are incorrect as shown by the mouse over
the 34x50 R is actually the 3x50 position

![pasted image at 2016_05_30 15_47](https://cloud.githubusercontent.com/assets/13413494/15651211/654f79a4-267e-11e6-94e5-95facad24a71.png)

**Comment by AJK-dev** [comment]
This issue was fixed along the way in the past couple of years without closing this issue.
