### ISSUE TITLE
"GTPL" ligand names

### ISSUE THREAD

**Issue by tamunro** [protwis/protwis#397]
There are two ligands in the structure database named with the prefix GTPL: GTPL9363 and GTPL9431. These appear to be their IDs from the "guide to pharmacology" database, and are not used in the literature. The names given in that database are BU72 and CCR2-RA-[R]. It might be worth adding a check that ligand names are used in several different databases.
Also, for BU72 (GTPL9363), the pubchem link is for the original structure (PDB ligand 4VO), which has since been revised (VF1):
https://pubchem.ncbi.nlm.nih.gov/compound/155804574
Maybe a routine could periodically check for updates to PDB entries.

**Comment by AJK-dev** [comment]
@tamunro thanks for your feedback. Given the size of our resource we are not able to curate all content continuously and therefore even more appreciate feedback from our user community. We have updated the records accordingly in our gpcrdb_data repo and it will be available in the next GPCRdb release.
Note: that the ligand names might change again in the future as the ligands are linked to multiple sources.
