### ISSUE TITLE
Phylogenetic tree crash after bootstrapping

### ISSUE THREAD

**Issue by AlexanderHauser** [protwis/protwis#40]
Phylogenetic tree cannot be calculated with 10 or 100 bootstrapping replicas on big selections (e.g. Class A - all TMs), which presumable leads to a server crash/ error on a local machine:

![snip20160531_1](https://cloud.githubusercontent.com/assets/13413494/15677199/91f59a44-2749-11e6-9e5d-4dc6a0e858ee.png)

**Comment by cmunk** [comment]
Fixed
