### ISSUE TITLE
Superpositioning workflow for homology models

### ISSUE THREAD

**Issue by AJK-dev** [protwis/protwis#411]
Based on feedback from the EFMC workshop:

It would be nice to be able to superpose homology models/refined structures as well.

**Comment by pszgaspar** [comment]
We plan to update the way we store models, with that we will have the superpositioning workflow extended to them

**Comment by pszgaspar** [comment]
Implemented in https://github.com/protwis/protwis/commit/e404a2795189cfc5d855ded60aa7e39d7d24f679 closing this issue
