### ISSUE TITLE
GN annotation fails for some GPCR structures

### ISSUE THREAD

**Issue by AJK-dev** [protwis/protwis#413]
**Feedback from @dominiquesydow:**

Using [gpcrdb.org](http://gpcrdb.org/) works for most PDB files but fails for example for the following PDBs:

- 6oik - Clear error “413 Request Entity Too Large”
Unclear errors (e.g. "Your XML file was empty" referring to the XML blast output)
- 6u1n
- 7eo4
- 7t10
- 6ddf
- 7v68
- 7ejx

 
Example command:
`curl -X POST -F pdb_file=@6oik.pdb https://gpcrdb.org/services/structure/assign_generic_numbers`

Additional Idea to have a function/URL to directly grab PDBs from GPCRdb with annotated GNs without upload (a bit like the ServePDB we already have)?

**Comment by AJK-dev** [comment]
The fix by @pszgaspar fixes all issues that raised the "unclear errors" 🎉 (now already online in GPCRdb)

For the first issue (413 Request Entity Too Large) with PDB 6oik, you need to adjust the maximum upload size for files.
For **Nginx** this can be done by adding the following to the **http** section in  _/etc/nginx/nginx.conf_
`client_max_body_size 5M;`

**Comment by dominiquesydow** [comment]
Hi @AJK-dev and @pszgaspar, thank you very much for this fix!
