### ISSUE TITLE
Missing generic number translations for loop segments

### ISSUE THREAD

**Issue by AlexanderHauser** [protwis/protwis#43]
_Residue numbers/Residue tables_

is missing generic numbers for loop segments of selected receptors.

![image](https://cloud.githubusercontent.com/assets/13413494/15828980/e6a2880a-2c11-11e6-9bdc-825cca1a338f.png)

**Comment by AJK-dev** [comment]
Still relevant, needs to be updated together with other new GN segments. In addition, a filter needs to be added to distinguish between GPCR and G protein residue numbering schemes.

**Comment by AJK-dev** [comment]
Resolved by @fosfataza (see PR #156 ) and also online.
