### ISSUE TITLE
Downloading receptor / peptide ligand pairs

### ISSUE THREAD

**Issue by donovanr** [protwis/protwis#447]
Hi, I'm new to using the site and would like to download the AA seqs of all receptor / peptide ligand pairs from https://gpcrdb.org/ligand/endogenousbrowser/

I see UniProt IDs for the receptors, but am having trouble programmatically using the ligand names as keys to grab the sequences.  Is there a clean way to do this?

**Comment by pszgaspar** [comment]
Hi @donovanr,
Apologies for the very late reply. We somehow missed this issue. We will shortly implement an API call that can handle this type of request. We will post here as soon as it is available online.

**Comment by Jimmy-A-Caroli** [comment]
Hi @donovanr,

the query you asked has been implemented and it is currently available in build version of GPCRdb, in the API section under the tag /services/ligands/endogenousligands/.

Here you will be able to retrieve data information for both small molecules and peptide ligands, in a downloadable json format structures this way:
    "receptor"
    "ligand_name"
    "sequence"
    "ligand_type"
    "endogenous_status"
    "potency_ranking"
    
Hope this helps
