### ISSUE TITLE
downloading data of ligands in csv by receptor query is unclean

### ISSUE THREAD

**Issue by syedzayyan** [protwis/protwis#466]
I am trying to get a list of ligands that binds to a particular receptor from the gpcrdb. However, the downloaded CSV file is not structured properly. Primarily there are many columns but the header only contains only a few. I have managed to see the event listener on download:

```
function() {
  var checked_data = table_potency.rows('.alt_selected').data();
  var checked_data = table_potency.rows('.alt_selected').data();
  var csv_data = [];
  csv_data.push('ChEMBL ID;Receptor;Species;Purchasable;No. records;Assay type;Min.;Average;Max.;Unit;Mol. weight;Rot. Bonds;H don;H acc;LogP;Smiles')
  for (i = 0; i < checked_data.length; i++) {
    var csv_row = []
    for (j = 1; j < checked_data[i].length; j++) {
      var div = document.createElement("div");
      div.innerHTML = checked_data[i][j];
      if (typeof div.innerText !== "undefined") {
        csv_row.push(div.innerText.replace(/\s+/g, ''));
      } else {
        csv_row.push(div.textContent.replace(/\s+/g, ''));
      }
    }
    csv_data.push(csv_row.join(';'));
  }
  var csv_string = csv_data.join("\n");
  if (window.navigator.msSaveOrOpenBlob) {
    var blob = new Blob([csv_string]);
    window.navigator.msSaveOrOpenBlob(blob, 'target_ligand_potency_data.csv');
  } else {
    var a = document.createElement('a');
    a.href = 'data:attachment/csv,' + encodeURIComponent(csv_string);
    a.target = '_blank';
    a.download = 'target_ligand_data.csv';
    document.body.appendChild(a);
    a.click();
  }
}
```

The push command is the problem since it's not including all the columns. Secondly, some of the rows happen to have extra columns. I think it is a formatting issue coming from the Assay description where there might be semi-colons.

My question is. Is there an API I could call that returns a JSON for me to clean and process a little easier? I have looked at the Swagger UI but it does not have anything to do with the ligand query or maybe I have missed something. 

Edit: I think the second issue could be solved if it were a TSV instead of CSV

**Comment by Jimmy-A-Caroli** [comment]
We are in the process of implementing this specific dedicated query in n the API section of GPCRdb (https://gpcrdb.org/services/) with the upcoming new release of the database. You can try it on our build server (https://build.gpcrdb.org/services/), looking for the query structure /services/ligands/{prot_name}/

The query is structured to get as input a protein entry name, and return a json of the ligand interacting with it, both name and ligand type. If more data is needed for the query and your analysis please let us know, so we can tweak the query function.

Thanks!

**Comment by syedzayyan** [comment]
Hello, many thanks for the reply. 

That helps very much. I was additionally looking for Smiles, the assay information (p-Value(-log); Acitivity Type; Acitivity Relation; Acitivity Value; Assay type; Assay desc; Source) and the DOI links (if any). It would be really helpful if there was a distinction if the ligands were agonists or antagonists, like Guide to Pharmacology has, but I understand that would be a massive undertaking. 

Thanks!

**Comment by Jimmy-A-Caroli** [comment]
We will implement the mentioned data fetches in the upcoming days for the new build. 
Thanks for pointing out the use cases and help us improve our services.

**Comment by syedzayyan** [comment]
Hello Everyone!

Thank you for the assay information. I got a chance to look at the code and the new dev build. It still does not have the DOI links. I presume it's a serializing issue because there are many DOIs for each ligand. I was thinking maybe assay information and other chemical information could be added but in the form of a query:

xxxasf/services/ligands/{prot_name}?req="assayinfo"

I had a couple of questions:
- Can external people contribute to this, if so how?
- Is there any plans to maybe do a separation of concerns situation where the frontend is built in React?
- Are there any plans for integrating Rust into the API?

**Comment by Jimmy-A-Caroli** [comment]
Hello @syedzayyan!

We are currently pushing the new implementation of this query that also reports DOIs for the ligands (when available), so this will probably be available in the build server in the next hours/days. We still plan to have a new build coming out soon too.

GPCRdb is a fully open source project and, while the dev team is constantly at work to improve, fix and develop new features, we are happy to have external contributions to our project. To do this, just fork the repo into your local and open a PR once you feel you have improved the codebase. We will go through that, revise it and make comments if needed and discuss the code, then proceed with the implementation in the main branch if everything checks. 

For what concerns Rust and React, we have plans for the framework and general updates, but sadly these two are, as far as I know, not really in our radar for future implementations.

**Comment by syedzayyan** [comment]
Hello!

I just have another question. There are unique assay types but they are somewhat arbitrarily indexed as 'B', 'F', 'A', 'U' . 

<img width="1007" alt="Screenshot 2023-03-07 at 12 13 54" src="https://user-images.githubusercontent.com/44922710/223419094-6067ef70-f738-4925-967e-37bef18915ad.png">

Is there a way of decoding them?

**Comment by Jimmy-A-Caroli** [comment]
Hello @syedzayyan,

the nomenclature you are looking at is directly derived from ChEMBL and it translates as follows:
**B** means **Binding**
**F** means **Functional**
**A** means **ADME**
**U** means **Unclassified**

Hope this helps
