### ISSUE TITLE
A Server Error

### ISSUE THREAD

**Issue by ZhunanStevenSun** [protwis/protwis#515]
<img width="1123" alt="Screenshot 2023-12-28 at 21 23 43" src="https://github.com/protwis/protwis/assets/152196992/effc2972-9b59-4cba-aa9b-9ebf4f333f10">
Hi, I just found out that I couldn't get access to the GPCRDB website, with the web page showing a 'Server error'. I asked someone else to try to access the URL, but he couldn't do it either. So I am pretty sure it is not a problem from my end.
Could you please deal with the problem? Thank you so much!

**Comment by pszgaspar** [comment]
Hi, 
Thanks for raising the issue. It was a disk space problem on the server. Fixed now.
Best,
Gaspar
