### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Gaoyuan-Liu-712** [protwis/protwis#520]
Hi,

I encountered this server error, the url I used is  https://gpcrdb.org/  
or was it something wrong on your end?

<img width="864" alt="Screen Shot 2024-02-08 at 3 37 32 PM" src="https://github.com/protwis/protwis/assets/68889787/cb6fdbc7-1287-4c5a-bd2e-ff32c45ddc6e">

**Comment by pszgaspar** [comment]
Thanks for raising the issue. It is fixed now
