### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by JunjieZhang12138** [protwis/protwis#521]
![Uploading 1707442853976.png…]()

Hi, I just found out that I couldn't get access to the GPCRDB website, with the web page showing a 'Server error'. I asked someone else to try to access the URL, but he couldn't do it either. So I am pretty sure it is not a problem from my end. Could you please deal with the problem? Thank you so much!

**Comment by pszgaspar** [comment]
Thanks for raising the issue. It is fixed now, same as #520
